parameters:
#    ehrgeiz_deal.example.class: Ehrgeiz\DealBundle\Example

services:
#    ehrgeiz_deal.example:
#        class: %ehrgeiz_deal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
